### ISSUE TITLE
Cards get shown after they have been learnt

### ISSUE THREAD

**Issue by memeToasty** [kioku-project/kioku#67]
**Description:**
When a card has been learnt, there is a time of 1-2 seconds, where the first page of this card is shown. After that the application returns to it's intended behavior.

**Steps to reproduce:**
1. Create a card with at least 2 sides.
2. Learn the card
3. You will experience the mentioned issue

**Comment by Julian702** [comment]
For me, this short loading time is significantly shorter in the local development environment (maximum half a second). Nevertheless, this is of course not very pleasant. I will investigate whether this can be eliminated only by changes to the frontend. It may also be necessary to make changes to our SRS service, as it can currently only return the next card. Even apart from this visual error, it would be an idea to preload the next card(s) in the background to reduce loading times.
